services:
  github-runner:
    image: ghcr.io/tamdinh/docker-github-actions-runner-android:expo57-node22-android36-v1
    restart: unless-stopped
    environment:
      REPO_URL: ${REPO_URL:-https://github.com/tamdinh/dokploy-mobile}
      RUNNER_TOKEN: ${RUNNER_TOKEN:-}
      ACCESS_TOKEN: ${ACCESS_TOKEN:-}
      EXPO_TOKEN: ${EXPO_TOKEN:-}
      RUNNER_NAME: ${RUNNER_NAME:-expo-android-runner-dokploy-mobile}
      RUNNER_WORKDIR: ${RUNNER_WORKDIR:-/runner/_work}
      RUNNER_LABELS: ${RUNNER_LABELS:-self-hosted,linux,x64,expo,android,web,vps,expo-android-runner}
      CONFIGURED_ACTIONS_RUNNER_FILES_DIR: /runner-data
      DISABLE_AUTOMATIC_DEREGISTRATION: "true"
      ANDROID_HOME: /usr/local/lib/android/sdk
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
      ANDROID_NDK_HOME: /usr/local/lib/android/sdk/ndk/27.1.12297006
      JAVA_HOME: /usr/lib/jvm/temurin-17-jdk-amd64
    volumes:
      - runner-data:/runner-data
      - gradle-cache:/root/.gradle
      - maven-cache:/root/.m2
      - npm-cache:/root/.npm
      - pnpm-cache:/root/.local/share/pnpm
      - expo-cache:/root/.expo

volumes:
  runner-data:
  gradle-cache:
  maven-cache:
  npm-cache:
  pnpm-cache:
  expo-cache:
